apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: order-service
  namespace: staging
spec:
  releaseName: order-service
#  targetNamespace: staging
#  install:
#    createNamespace: true
  chart:
    spec:
      chart: order-service
      sourceRef:
        kind: HelmRepository
        name: fvxiaoyi
        namespace: flux-system
  interval: 1m
  values:
    image:
      tag: 27 # {"$imagepolicy": "flux-system:order-service:tag"}
    replicaCount: 1
