apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Receiver
metadata:
  name: webapp
  namespace: flux-system
spec:
  type: generic
  secretRef:
    name: webhook-token
  resources:
    - kind: HelmRepository
      name: fvxiaoyi
      namespace: flux-system
    - kind: ImageRepository
      name: order-service
      namespace: flux-system
    - kind: GitRepository
      name: flux-system
      namespace: flux-system