apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: order-service
spec:
  image: ebinsu/order-service
  interval: 12h0m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: order-service
spec:
  imageRepositoryRef:
    name: order-service
    namespace: flux-system
  policy:
    numerical:
      order: "asc"